version: ''

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mindvibe_db}
      POSTGRES_USER: ${POSTGRES_USER:-mindvibe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_strong_password}

  web:
    build: .
    command: gunicorn mindvibe_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:-your_default_django_secret_key}
      DEBUG: ${DEBUG:-0}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
      DATABASE_URL: ${DATABASE_URL:-postgres://mindvibe_user:your_strong_password@db:5432/mindvibe_db}
      PROMPTPAY_ID: "${PROMPTPAY_ID:-0954472922}"  
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
