# Generated by Django 4.2.9 on 2025-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='rental_duration_days',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='order',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดเช่า'),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มเช่า'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขพัสดุ (คืน)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ค่าจัดส่ง'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขพัสดุ (ส่ง)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาต่อวัน (ณ ตอนสั่ง)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='ที่อยู่สำหรับจัดส่ง'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังดำเนินการ'), ('shipped', 'จัดส่งแล้ว'), ('rented', 'กำลังเช่า'), ('return_pending', 'รอส่งคืน'), ('return_received', 'ได้รับคืนแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('failed', 'การชำระเงินล้มเหลว')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
