# Generated by Django 4.2.9 on 2025-05-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_payment_note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ (การชำระเงิน)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่โอน (ตามที่แจ้ง)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/%Y/%m/', verbose_name='สลิปการโอนเงิน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='ยืนยันการชำระเงินแล้ว'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', editable=False, max_length=50, verbose_name='วิธีชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('waiting_for_approval', 'รอตรวจสอบสลิป'), ('processing', 'กำลังดำเนินการ'), ('shipped', 'จัดส่งแล้ว'), ('rented', 'กำลังเช่า'), ('return_pending', 'รอส่งคืน'), ('return_received', 'ได้รับคืนแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('failed', 'การชำระเงินล้มเหลว/สลิปไม่ถูกต้อง')], default='pending', max_length=30, verbose_name='สถานะ'),
        ),
    ]
