# Generated by Django 4.2.9 on 2025-05-05 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0003_remove_order_payment_id_order_admin_payment_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่ (สำหรับบันทึก)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ข้อมูลโปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'ข้อมูลโปรไฟล์ผู้ใช้',
            },
        ),
    ]
