# Generated by Django 4.2.9 on 2025-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_initiated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่แจ้งส่งคืน'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_slip',
            field=models.ImageField(blank=True, null=True, upload_to='return_slips/%Y/%m/', verbose_name='รูปถ่าย/สลิปส่งคืน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอชำระเงิน'), ('waiting_for_approval', 'รอตรวจสอบสลิป'), ('processing', 'กำลังดำเนินการ'), ('shipped', 'จัดส่งแล้ว'), ('rented', 'กำลังเช่า'), ('return_shipped', 'ลูกค้าส่งคืนแล้ว'), ('return_received', 'ได้รับคืนแล้ว'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('failed', 'การชำระเงินล้มเหลว/สลิปไม่ถูกต้อง')], default='pending', max_length=30, verbose_name='สถานะ'),
        ),
    ]
