# Generated by Django 4.2.9 on 2025-05-07 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0005_order_return_initiated_at_order_return_slip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Rental Order', 'verbose_name_plural': 'Rental Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ('name',), 'verbose_name': 'Outfit', 'verbose_name_plural': 'Outfits'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used for URL (auto-generated if blank)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_payment_note',
            field=models.TextField(blank=True, verbose_name='Admin Payment Note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payment Confirmed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date/Time (Reported)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', editable=False, max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/%Y/%m/', verbose_name='Payment Slip'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rental End Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rental Start Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_initiated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return Initiated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_slip',
            field=models.ImageField(blank=True, null=True, upload_to='return_slips/%Y/%m/', verbose_name='Return Slip/Photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Return Tracking No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Tracking No.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('waiting_for_approval', 'Awaiting Approval'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('rented', 'Rented'), ('return_shipped', 'Return Shipped'), ('return_received', 'Return Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed/Invalid')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfits.order', verbose_name='Rental Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='outfits.outfit', verbose_name='Outfit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Day (at time of order)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='outfits.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Outfit Name'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rental Price per Day'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Saved Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
