# Generated by Django 4.2.9 on 2025-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0006_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('waiting_for_approval', 'Waiting for Payment Approval'), ('failed', 'Payment Failed'), ('processing', 'Processing'), ('shipped', 'Shipped to Customer'), ('rented', 'Rented (With Customer)'), ('return_shipped', 'Return Shipped by Customer'), ('return_received', 'Return Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
