# Generated by Django 5.2 on 2025-04-23 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0011_alter_outfit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(blank=True, help_text='ใช้สำหรับ URL (จะสร้างให้เองถ้าเว้นว่าง)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ('name',), 'verbose_name': 'ชุด', 'verbose_name_plural': 'ชุด'},
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='is_rented',
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อชุด'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคาเช่าต่อวัน'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='outfits.category', verbose_name='หมวดหมู่'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อจริง')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดรวม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังดำเนินการ'), ('rented', 'กำลังเช่า'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก'), ('failed', 'การชำระเงินล้มเหลว')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='วิธีชำระเงิน')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID (จาก Gateway)')),
                ('paid', models.BooleanField(default=False, verbose_name='ชำระเงินแล้ว')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'คำสั่งเช่า',
                'verbose_name_plural': 'คำสั่งเช่า',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อวัน (ณ ตอนสั่ง)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('rental_start_date', models.DateField(verbose_name='วันที่เริ่มเช่า')),
                ('rental_duration_days', models.PositiveIntegerField(default=1, verbose_name='จำนวนวันเช่า')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfits.order', verbose_name='คำสั่งเช่า')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='outfits.outfit', verbose_name='ชุด')),
            ],
            options={
                'verbose_name': 'รายการในคำสั่งเช่า',
                'verbose_name_plural': 'รายการในคำสั่งเช่า',
            },
        ),
    ]
